sonar.projectKey=antoine-bouteiller_autoscan
sonar.organization=antoine-bouteiller

# Source directories
sonar.sources=src
sonar.tests=tests

# TypeScript specific settings
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.test.exclusions=tests/**

# Coverage exclusions
sonar.coverage.exclusions=tests/**,**/integrations/**,**/providers/**,**/config/**,**/controllers/**,**/jobs/**,**/validators/**,**/errors/**,**/core/**
