import { inversedEntriesOf } from '@/utils/object'

// ISO 639-1 (2-character codes)
export const ISO1 = [
  'ar',
  'bg',
  'bn',
  'cs',
  'da',
  'de',
  'el',
  'en',
  'es',
  'et',
  'fa',
  'fi',
  'fr',
  'hi',
  'hr',
  'hu',
  'id',
  'is',
  'it',
  'ja',
  'ko',
  'lt',
  'lv',
  'mt',
  'nl',
  'no',
  'pl',
  'pt',
  'ro',
  'ru',
  'sk',
  'sl',
  'sr',
  'sv',
  'tr',
  'zh',
] as const

// ISO 639-2/T (3-character terminologic codes)
export const ISO2T = [
  'ara',
  'ben',
  'bul',
  'ces',
  'dan',
  'deu',
  'ell',
  'eng',
  'est',
  'fas',
  'fin',
  'fra',
  'hin',
  'hrv',
  'hun',
  'ind',
  'isl',
  'ita',
  'jpn',
  'kor',
  'lav',
  'lit',
  'mlt',
  'nld',
  'nor',
  'pol',
  'por',
  'ron',
  'rus',
  'slk',
  'slv',
  'spa',
  'srp',
  'swe',
  'tur',
  'zho',
] as const

// ISO 639-2/B (3-character bibliographic codes)
// Only includes languages where B and T codes differ
export const ISO2B = ['chi', 'cze', 'dut', 'fre', 'ger', 'gre', 'ice', 'per', 'rum', 'slo'] as const

// ISO 639-2/B to ISO 639-2/T mapping
export const iso2BToIso2T = {
  chi: 'zho',
  cze: 'ces',
  dut: 'nld',
  fre: 'fra',
  ger: 'deu',
  gre: 'ell',
  ice: 'isl',
  per: 'fas',
  rum: 'ron',
  slo: 'slk',
} as const

export const iso2TToIso2B = inversedEntriesOf(iso2BToIso2T)

export type ISOCode1 = (typeof ISO1)[number]
export type ISOCode2T = (typeof ISO2T)[number]
export type ISOCode2B =
  | (typeof ISO2B)[number]
  | Exclude<ISOCode2T, (typeof iso2BToIso2T)[keyof typeof iso2BToIso2T]>

export type ISOCode2 = ISOCode2B | ISOCode2T

// ISO 639-1 to ISO 639-2/T mapping
export const iso1ToIso2T: Record<ISOCode1, ISOCode2T> = {
  ar: 'ara',
  bg: 'bul',
  bn: 'ben',
  cs: 'ces',
  da: 'dan',
  de: 'deu',
  el: 'ell',
  en: 'eng',
  es: 'spa',
  et: 'est',
  fa: 'fas',
  fi: 'fin',
  fr: 'fra',
  hi: 'hin',
  hr: 'hrv',
  hu: 'hun',
  id: 'ind',
  is: 'isl',
  it: 'ita',
  ja: 'jpn',
  ko: 'kor',
  lt: 'lit',
  lv: 'lav',
  mt: 'mlt',
  nl: 'nld',
  no: 'nor',
  pl: 'pol',
  pt: 'por',
  ro: 'ron',
  ru: 'rus',
  sk: 'slk',
  sl: 'slv',
  sr: 'srp',
  sv: 'swe',
  tr: 'tur',
  zh: 'zho',
}

// ISO 639-2/T to ISO 639-1 reverse mapping
export const iso2ToIso1: Record<ISOCode2, ISOCode1> = {
  ara: 'ar',
  ben: 'bn',
  bul: 'bg',
  ces: 'cs',
  chi: 'zh',
  cze: 'cs',
  dan: 'da',
  deu: 'de',
  dut: 'nl',
  ell: 'el',
  eng: 'en',
  est: 'et',
  fas: 'fa',
  fin: 'fi',
  fra: 'fr',
  fre: 'fr',
  ger: 'de',
  gre: 'el',
  hin: 'hi',
  hrv: 'hr',
  hun: 'hu',
  ice: 'is',
  ind: 'id',
  isl: 'is',
  ita: 'it',
  jpn: 'ja',
  kor: 'ko',
  lav: 'lv',
  lit: 'lt',
  mlt: 'mt',
  nld: 'nl',
  nor: 'no',
  per: 'fa',
  pol: 'pl',
  por: 'pt',
  ron: 'ro',
  rum: 'ro',
  rus: 'ru',
  slk: 'sk',
  slo: 'sk',
  slv: 'sl',
  spa: 'es',
  srp: 'sr',
  swe: 'sv',
  tur: 'tr',
  zho: 'zh',
}
